Add developer support for using next.js to serve generated static files
khoj-ai/khoj pull request #814
Opened 2024-06-12 09:19 UTC by sabaimran

# Incoming

To improve the developer experience for front-end development, we're migrating to [Next.js](https://nextjs.org/). In order to do this migration page-by-page, we're using static site generation via Next.js. This also helps us avoid making cross site requests from front-end to back-end for the time being, while giving a ramp to separating out server and client if needed for scale down the road.

Dev instructions for using the `next.js` setup are in the added README. 

This adds scaffolding for including the built files in the python package as well as the docker images. Docker setup has been tested locally. In order to verify the build is working as expected, we can navigate to the `{khoj_host}:42110/experimental` and verify that the experiment page comes up.

This setup works with serving static files included in the `src/interface/web` folder from the Django app. The key bit for understanding the setup is in the `yarn export` command in `package.json`.

2024-06-12 13:19 UTC, sabaimran commented on src/interface/web/package.json
> +    "collectstatic": "bash -c 'pushd ../../../ && source .venv/bin/activate && python3 src/khoj/manage.py collectstatic --noinput && deactivate && popd'",
make windows-compatible shortcuts

2024-06-12 13:21 UTC, sabaimran commented on src/interface/web/next.config.mjs
> +const nextConfig = {
see if we can make it easier to switch prod/dev config

2024-06-12 16:17 UTC, sabaimran commented on .github/workflows/dockerize.yml
> +  pull_request:
Remove this and make PR builds optional?

2024-06-18 04:03 UTC, MythicalCow requested changes
Very exciting work here towards upgrading our system. Nice work! Left a few changes for making documentation easier to follow and fixing windows usage.

2024-06-18 04:03 UTC, MythicalCow commented on src/interface/web/package.json
> +    "windowswatch": "nodemon --watch . --ext js,jsx,ts,tsx,css --ignore 'out/**/*' --exec 'yarn windowsexport'"
So things get a bit messy but here are the corrected commands for windows:
```
    "collectstatic": "bash -c 'pushd ../../../ && source .venv/bin/activate && python3 src/khoj/manage.py collectstatic --noinput && deactivate && popd'",
    "windowscollectstatic": "cd ..\\..\\.. && .\\.venv\\Scripts\\Activate.bat && py .\\src\\khoj\\manage.py collectstatic --noinput && .\\.venv\\Scripts\\deactivate.bat && cd ..",
    "cicollectstatic": "bash -c 'pushd ../../../ && python3 src/khoj/manage.py collectstatic --noinput && popd'",
    "export": "yarn build && cp -r out/ ../../khoj/interface/built && yarn collectstatic",
    "windowsexport": "yarn build && xcopy out ..\\..\\khoj\\interface\\built /E /Y && yarn windowscollectstatic",
    "ciexport": "yarn build && cp -r out/ ../../khoj/interface/built && yarn cicollectstatic",
    "watch": "nodemon --watch . --ext js,jsx,ts,tsx,css --ignore 'out/**/*' --exec 'yarn export'",
    "windowswatch": "nodemon --watch . --ext js,jsx,ts,tsx,css --ignore 'out/**/*' --exec \"yarn windowsexport\""
```

2024-06-18 12:48 UTC, sabaimran commented on src/interface/web/README.md
Ah, good catch! I removed the need for the lines to comment/uncomment, so #3 is no longer an issue.

Would you still have the stack trace you encountered for #1 by any chance? No worries if not.

2024-06-19 17:22 UTC, debanjum commented on src/interface/web/next.config.mjs
> +            }
These two s3 buckets shouldn't be required anymore? Those buckets are deprecated

2024-06-21 07:16 UTC, sabaimran commented on src/interface/web/app/favicon.ico
This is just because the favicon currently isn't being loaded in. As it's just an experimental page, I'll defer this for now.

2024-06-22 14:42 UTC, merged